### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by 7kayoh** [7kayoh/commander#12]
The title speaks itself, but I'll explain with details. Right now, Commander is living a happy life, being recognized by users, developers and much more. There's one big concern we are having, which is the overall code quality. Here are my commitments about how our code should be, how the API should be, and what is our actual goals in the development side.

First, we should prevent the user from tampering with the source code in order to achieve something, like updating Commander. They should **never** ever get to touch the source code just to update the system. So, no copy & pasting for scripts, nor for the settings. Everything like that should be done with just **one** button click.

Second, we should take control of how the developer code for us. In order to make sure our philosophy is still valid; we should never make the developer have to implement their own system solely for their command. This will violate one of our goals, which is being lightweight. Apart from that, having them to rely on our API/Services module, we have much greater code quality control, as well as being able to ensure all packages will function, no matter how old it is.

Lastly, as Commander is being actively developed, we should make sure our code is good enough for everybody else to take references.

**Comment by cursecodes** [comment]
May I add that if you are going to try to improve the Commander code base, an actual open-source version of Latte (I'm curious) would be appreciated.

**Comment by va1kio** [comment]
Latte is actually open sourced! The reason why I don't mention about it, or make a repository for it is because it's too small and too meaningless to open source it as a separated project. In fact, I'd rather call it a loader that enforces people to write in a modular pattern.

However, I plan to recode Latte to be an actual framework in the future, but that is not in our priority list for now.
