### ISSUE TITLE
The donation buttons should give you a URL if AllowThirdPartySales game setting is disabled.

### ISSUE THREAD

**Issue by ccuser44** [7kayoh/commander#55]
In most games ThirdPartySales are disabled. Clicking the donation button on said games does nothing. It should be made so that if such is the case it should give you an alternative URL to the game passes to donate.

**Comment by va1kio** [comment]
I am very unsure whether is there a method to detect it, are you able to suggest a way to implement that?

**Comment by jaydensar** [comment]
> I am very unsure whether is there a method to detect it, are you able to suggest a way to implement that?

There's [workspace.AllowThirdPartySales](https://developer.roblox.com/en-us/api-reference/property/Workspace/AllowThirdPartySales) but that doesn't seem to work from what i've tried.

**Comment by ccuser44** [comment]
I think there appears a warning in the logs and you can check it with logservice. But again this is quite hacky. Here is a dev forum post where there is a screenshot of the warning in the logs https://devforum.roblox.com/t/introducing-two-game-security-settings-third-party-sales-cross-game-teleports/674209/48

Another way could be to just show the link always.

A third option could be to display the link under the purpchase prompt. But when(if) the item is purpchased then you hide the link. The link should be contained in a box which is smaller than the purpchase prompt and at the same position. It should also have a button to close it.

**Comment by Ivanmatthew** [comment]
> > I am very unsure whether is there a method to detect it, are you able to suggest a way to implement that?
> 
> There's [workspace.AllowThirdPartySales](https://developer.roblox.com/en-us/api-reference/property/Workspace/AllowThirdPartySales) but that doesn't seem to work from what i've tried.

It does work, however only per server script.

**Comment by va1kio** [comment]
My goto at this is probably assigning a key to the Settings module called `.IsThirdPartySalesEnabled`, which will be assigned to `workspace.AllowThirdPartySales`.

As the system will fire firstRun to the person in authority with the Settings module, we can determine whether is it disabled with `Settings.IsThirdPartySalesEnabled`

**Comment by Ivanmatthew** [comment]
I created a mock script for example:

`
for i,v in pairs(Items) do
	local Button = Latte.Components.OutlinedButton.new(v.Value, "Donate " .. tostring(v.Value) .. " Robux", Page, function()
		if workspace.AllowThirdPartySales then
			Latte.Modules.Services.MarketplaceService:PromptGamePassPurchase(Latte.Modules.Services.Players.LocalPlayer, v.Id)
		else
			-- popup to link for gamepass donation thing?
		end
	end)
	Button.Size = UDim2.new(1, -20, 0, Button.Size.Y.Offset)
	Button.LayoutOrder = i + 1
end
`

**Comment by ccuser44** [comment]
> 
> 
> My goto at this is probably assigning a key to the Settings module called `.IsThirdPartySalesEnabled`, which will be assigned to `workspace.AllowThirdPartySales`.
> 
> As the system will fire firstRun to the person in authority with the Settings module, we can determine whether is it disabled with `Settings.IsThirdPartySalesEnabled`

`workspace.AllowThirdPartySales` doesn't actually tell wether or not ThirdPartySales can be done. There is one way to known via LogService but that is hacky. Also workspace.AllowThirdPartySales will be deprecated.


The correct way to do this would to display the prompt with the link below the purpchase prompt. When the purpchase prompt gets clicked it would destroy the URL prompt also. And the URL prompt should have a close button also. The URL should be stored in a TextBox instead of a TextLabel to allow copying the link.

Here is some pseudo code explaining how it should be implemented.
`
local function GetGamepassUrlFromId(Id)
local BaseUrl = "https://www.roblox.com/game-pass/%d/name_holder"
return string.format(BaseUrl, Id)
end

local function OnDonationClicked()
local Event = Instance.new("Event")
-- // Display Prompt
PromtText.Text = GetGamepassUrlFromId(GamepassId)

local Evn1, Evn2 = MarketplaceService.PromptGamePassPurchaseFinished:Connect(function() Event:Fire() end), PromptCloseButton.Activated:Connect(function() Event:Fire() end)

xpcall(function()
MarketplaceService:PromptGamePassPurchase(LocalPlayer, GamepassId)
end, warn)

Event:Wait()
Event:Destroy()
Evn1:Disconnect()
Evn2:Disconnect()
-- // Destroy Prompt
end


DonateButton.Clicked:Connect(OnDonationClicked)
`

**Comment by Ivanmatthew** [comment]
> > My goto at this is probably assigning a key to the Settings module called `.IsThirdPartySalesEnabled`, which will be assigned to `workspace.AllowThirdPartySales`.
> > As the system will fire firstRun to the person in authority with the Settings module, we can determine whether is it disabled with `Settings.IsThirdPartySalesEnabled`
> 
> `workspace.AllowThirdPartySales` doesn't work anymore.
> 
> The correct way to do this would to display the prompt with the link below the purpchase prompt. When the purpchase prompt gets clicked it would destroy the URL prompt also. And the URL prompt should have a close button also. The URL should be stored in a TextBox instead of a TextLabel to allow copying the link.
> 
> Here is some pseudo code explaining how it should be implemented.
> 
> ```
> 
> local function GetGamepassUrlFromId(Id)
> local BaseUrl = "https://www.roblox.com/game-pass/%d/name_holder"
> return string.format(BaseUrl, Id)
> end
> 
> local function OnDonationClicked()
> local Event = Instance.new("Event")
> -- // Display Prompt
> PromtText.Text = GetGamepassUrlFromId(GamepassId)
> 
> local Evn1, Evn2 = MarketplaceService.PromptGamePassPurchaseFinished:Connect(function() Event:Fire() end), PromptCloseButton.Activated:Connect(function() Event:Fire() end)
> 
> xpcall(function()
> MarketplaceService:PromptGamePassPurchase(LocalPlayer, GamepassId)
> end, warn)
> 
> Event:Wait()
> Event:Destroy()
> Evn1:Disconnect()
> Evn2:Disconnect()
> -- // Destroy Prompt
> end
> 
> 
> DonateButton.Activated:Connect(OnDonationClicked)
> ```

How do you mean it doesn't work anymore? I've tried it and it seems to work everytime for me

**Comment by ccuser44** [comment]
> How do you mean it doesn't work anymore? I've tried it and it seems to work everytime for me
Even if it does Roblox said they will be deprecating it.

**Comment by Ivanmatthew** [comment]
> > How do you mean it doesn't work anymore? I've tried it and it seems to work everytime for me
> 
> Even if it does Roblox said they will be deprecating it.

they haven't deprecated it since november 20'th, till that time I think it would be safe to assume it would still work, and even if it were at that point then deprecated, you could always change the function on how to check if thirdparty sales are on

**Comment by ccuser44** [comment]
> > > How do you mean it doesn't work anymore? I've tried it and it seems to work everytime for me
> > 
> > 
> > Even if it does Roblox said they will be deprecating it.
> 
> they haven't deprecated it since november 20'th, till that time I think it would be safe to assume it would still work, and even if it were at that point then deprecated, you could always change the function on how to check if thirdparty sales are on

Just because they haven't deprecated it yet doesn't mean they won't very soon. Besides it is already confirmed that the property doesn't work some times and it has been buggy since it was introduced. There is no reason not to do the method I suggested as you do not lose anything if you do.

**Comment by LolloDev5123** [comment]
pee pee
