### ISSUE TITLE
Conmplete rewrite of the way player selectors work.

### ISSUE THREAD

**Issue by ccuser44** [7kayoh/commander#72]
Currently the player selectors return one player meaning you can only run a command on **one player**.

Most admin commands allow you to run a command on multiple players. Currently the only command that this works properly is the chat command.

Like the stuff inside API.Players.executeWithPrefix

**Comment by ccuser44** [comment]
Also the fact that the way the command request arguments is via sending a modal. This isn't quite ideal. You should rather have some way of getting the arguments in a more cohierent way. Like Adonis Admin does.

**Comment by ccuser44** [comment]
There should be like something like getarg(THEARGUMENTINDEX) and it yields until the arg is given by the player.

And a table showing the arg info.

**Comment by ccuser44** [comment]
But all of this should be backwards compatible for the time.

**Comment by va1kio** [comment]
?! Unsure what you mean by that, you are giving example of a chat-based administration system while Commander is a panel-based administration system. Both has a very different design and layout. As well as the target consumers.

Though, yes, I can see the inefficiency issue caused by having a new modal per each argument. In the future we will probably have it so you can build a form inside the modal (basically a list of user inputs), such as switches, checkboxes, textboxes, date picker, et cetera.

**Comment by ccuser44** [comment]
Yeah I kinda badly explained it.

So like when it asks you for the player you can only run the command on one player.

But commander has a chat command where you can run it on multiple players because it uses API.Players.executeWithPrefix.

I made a API.Players.executeWithPrefix in my pull #73 which would allow you to run the command on multiple players if implemented.




Like when you ask a player you can also type
nonadmins,random

all

admins

**Comment by ccuser44** [comment]
It's kinda hard to explain.

**Comment by va1kio** [comment]
FYI, Commander has a few commands that utilises executeWithPrefix, such as Message, SystemMessage, Hint, PrivateMessage.

**Comment by ccuser44** [comment]
yes. But it should work so that you could use the selectors on any command.

**Comment by ccuser44** [comment]
Also even though the use executeWithPrefix they can only use "all" , "others" or playername

However they should be able to use "all" "others" "admins" "nonadmins" "me" "random" and playername

And they can have many selectors at one. Like "others,Player1,nonadmins,random" like they seperate them with ","

**Comment by ccuser44** [comment]
And there should be some quick command execution window when you can pretype all the arguments in a quick way.
