### ISSUE TITLE
Add make Ban not save in datastore. Add PermBan

### ISSUE THREAD

**Issue by ccuser44** [7kayoh/commander#77]
You should add `"Permenant Ban"` command and it has the behavior of current `Ban` command. (Save the bans to the datastore like currently the `Ban` command does)

Remove Datastore from normal `Ban`.

In a lot of use cases you would want to ban a player only on the server.

Seperating `Ban` and `Permenant Ban` will also give you more control over how you punish.

**Comment by matsumooo** [comment]
Hm, we haven't tried out the storage API, so we are uncertain whether can we implement that, while ensuring unban will work for both datastore-based bans and server bans

**Comment by Nicklaus-s** [comment]
> In a lot of use cases you would want to ban a player only on the server.

Could this be possible using table functions, eg: `table.insert`, search the table for a newly joined player if so kick them. If I remember correctly table.insert only saves in the current server.

Would this be a possible way of making a server ban command?
