### ISSUE TITLE
Use ProfileService

### ISSUE THREAD

**Issue by SilentsReplacement** [7kayoh/commander#98]
Use ProfileService for commander data store handling. Bye

**Comment by Nicklaus-s** [comment]
the benefits for this would be: null

**Comment by SilentsReplacement** [comment]
either you can choose to say bs or actually learn the benefits

**Comment by 7kayoh** [comment]
We aren't going to change the data system anytime soon, until we've come up a "genius" and optimal solution to migrate existing data to the ProfileService.
